### PR TITLE
ci: stablize golangci-lint task 

### LINKED ISSUE #1005: [CI] Golangci-lint always failed and block the master branch
The `golangci-lint` always failed with the following log:
```
2023-04-10T12:04:03.2624074Z ##[group]Run golangci/golangci-lint-action@v3
2023-04-10T12:04:03.2624590Z with:
2023-04-10T12:04:03.2624835Z   version: v1.50.1
2023-04-10T12:04:03.2625462Z   github-token: ***
2023-04-10T12:04:03.2625807Z   only-new-issues: false
2023-04-10T12:04:03.2626098Z   skip-cache: false
2023-04-10T12:04:03.2626431Z   skip-pkg-cache: false
2023-04-10T12:04:03.2626784Z   skip-build-cache: false
2023-04-10T12:04:03.2627108Z ##[endgroup]
2023-04-10T12:04:03.4373345Z ##[group]prepare environment
2023-04-10T12:04:03.4383156Z Checking for go.mod: go.mod
2023-04-10T12:04:03.4470228Z Finding needed golangci-lint version...
2023-04-10T12:04:03.4470848Z Installing golangci-lint v1.50.1...
2023-04-10T12:04:03.4471712Z Downloading https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-linux-amd64.tar.gz ...
2023-04-10T12:04:03.6553301Z Cache not found for input keys: golangci-lint.cache-2779-1638c36cade87c81ee880ccc59e1db568edee554, golangci-lint.cache-2779-
2023-04-10T12:04:03.7869680Z [command]/usr/bin/tar xz --overwrite --warning=no-unknown-keyword --overwrite -C /home/runner -f /home/runner/work/_temp/0b6fff89-3882-4e7f-9bdd-e1587d92a863
2023-04-10T12:04:03.9943763Z Installed golangci-lint into /home/runner/golangci-lint-1.50.1-linux-amd64/golangci-lint in 542ms
2023-04-10T12:04:03.9944398Z Prepared env in 550ms
2023-04-10T12:04:03.9945885Z ##[endgroup]
2023-04-10T12:04:03.9946883Z ##[group]run golangci-lint
2023-04-10T12:04:03.9948238Z Running [/home/runner/golangci-lint-1.50.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
```
More detail [here](https://github.com/Gleiphir2769/pulsar-client-go/actions/runs/4657238383/jobs/8241639486?pr=4#step:3:1)

This is blocking the master branch currently.

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #1005.

### Modifications

1. Replace the usage of golangci-lint action with barely bin commands.
2. Support run with the specified version with one command `make lint` and store the binutil project-wise.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by shibd** [comment]
@tisonkun Please help explain why?

**Comment by shibd** [comment]
> > why
> 
> Why for what?
> 
> You can refer to the issue for the failure. Generally, we use a `v3` tag for golangci-lint action which is not fixed. So anything can be changed from upstream. This patch pinned the golangci-lint to v1.51.2 and does not use the action to ignore any bad case there.

FYI, we have fixed the version here.

https://github.com/apache/pulsar-client-go/pull/951/files

**Comment by Gleiphir2769** [comment]
Good work! @tisonkun 

But I am very curious why `httpclient` can pass the previous CI. It's introduced in 2021. It means the old golangci-lint we used has the ability for ignoring old files?

I do not find any golangci-lint doc for this so I can not understand why this happens. This is so weird.

**Comment by tisonkun** [comment]
> But I am very curious why httpclient can pass the previous CI. It has already been introduced in 2021. The old golangci-lint we used has the ability for ignoring old files?

I bump the golangci-lint to 1.51.2 because original 1.50.1 doesn't work locally for unknown reason - I don't spend time to figure it out but simply do a small version bump.

Besides, it's a false positive on bodyclose linter. There are a few false positive reports upstream, like https://github.com/timakin/bodyclose/issues/42.

**Comment by Gleiphir2769** [comment]
> Besides, it's a false positive on bodyclose linter. There are a few false positive reports upstream, like [timakin/bodyclose#42](https://github.com/timakin/bodyclose/issues/42).

I see. It's actually a false positive. Thanks!

**Pull request merged**
