### PR TITLE
add 0.8.1 changelog

### PR DESCRIPTION
**Pull request by freeznet**
### Motivation

Add 0.8.1 changelog

### CODE REVIEW

**Review by zymap — APPROVED** [review]

**Review by wolfstudy — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Comment by freeznet** [comment]
the failed CI related with https://github.com/apache/pulsar/pull/13885 and https://github.com/apache/pulsar/pull/14176, ignore and merge

**Comment by shubham1172** [comment]
@freeznet can you please share a tentative timeline for releasing v0.8.1?

**Comment by freeznet** [comment]
@shubham1172 thanks for asking, the RC1 voting is on going, and should be released in this week if no objections. you can check the voting here: https://lists.apache.org/thread/85p7339y14o2484f47hpprlzd5vrnnyj

**Comment by shubham1172** [comment]
This is helpful, thanks for sharing it @freeznet !

**Comment by freeznet** [comment]
@shubham1172 https://github.com/apache/pulsar-client-go/releases/tag/v0.8.1 is released.

**Comment by shubham1172** [comment]
Thank you @freeznet for you quick help! 🎉

**Pull request merged**
