### PR TITLE
Bump oauth2 package version to the latest in master

### PR DESCRIPTION
**Pull request by iorvd**
### Motivation

1. `github.com/dgrijalva/jwt-go` contains a known CVE [vulnerability](https://github.com/advisories/GHSA-w73w-5m7g-f7qc)
2. This dependency was replaced with another jwt package.
3. But `oauth2` package version wasn't updated in master, so `github.com/apache/pulsar-client-go` still depends on it at the moment:

image

### Modifications

Update the version of `oauth2` to the latest commit to that package

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

```
$ go get github.com/apache/pulsar-client-go/oauth2@fe3b7c4e445b
$ cd $(go env GOPATH)/pkg/mod/github.com/apache/pulsar-client-go/oauth2@v0.0.0-20211108044248-fe3b7c4e445b/
$ go mod why github.com/dgrijalva/jwt-go
```
image

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): yes, upgrades oauth2 package version to the latest in master
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no

### Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable
  - If a feature is not applicable for documentation, explain why? version update
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by wolfstudy** [comment]
Hello @iorvd It looks like [xxx](https://github.com/apache/pulsar-client-go/pull/713) is dealing with this, is this sufficeable?

**Review by wolfstudy — APPROVED** [review]

**Comment by wolfstudy** [comment]
Nice work!!

**Comment by wolfstudy** [comment]
It looks like #713  is dealing with this, is this sufficeable?

**Comment by iorvd** [comment]
> It looks like #713 is dealing with this

@wolfstudy Looks like it's [not](https://github.com/apache/pulsar-client-go/blob/master/go.mod#L8). But that's still a valid point, l'll update the version to the latest :)

**Pull request merged**
