### PR TITLE
[Issue 177] add multiple hosts support

### LINKED ISSUE #177: Not support multi pulsar cluster addresses
**Is your feature request related to a problem? Please describe.**
not support the use of pulsar cluster addresses?

**Describe the solution you'd like**

```
client, err := pulsar.NewClient(pulsar.ClientOptions{
    URL: "pulsar://p1.pulsar.com:6650,pulsar://p2.pulsar.com:6650,pulsar://p3.pulsar.com:6650",
})
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by freeznet**
Fixes #177 

Master Issue https://github.com/apache/pulsar/issues/3218

### Motivation

add multiple hosts support to go client

### Modifications

- add service uri & service name resolver
- add service name resolver to lookup service & rpc client
- add unit tests
- add integration tests

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by freeznet** [comment]
@wolfstudy PTAL, thanks

**Review by wolfstudy — COMMENTED** [review]
The logic LGTM +1, please merge master code and fix conflict

**Comment by wolfstudy** [comment]
@merlimat @cckellogg please review this change, thanks.

**Comment by Anonymitaet** [comment]
@freeznet I've added [docs](https://docs.google.com/document/d/1khRzbYDrDpOxtylc_SMzAsDn7f2m4fnrejxLU8fn2i4/edit#) for this PR, could u pls help review? Feedback b4 3/24 is highly appreciated, thanks.

**Pull request merged**
