### PR TITLE
[fix] [issue 1067] Fix the excessive dataChan capacity

### LINKED ISSUE #1067: [BUG] The capacity of dataChan is too big
Hi community. I noticed that the capacity of dataChan is too big. We make the `dataChan` with capacity `MaxPendingMessages`  and the account of pending messages actual in queue may exceed the limit by `MaxPendingMessages` a lot. 

This is because we use `publishSemaphore` instead of capacity of `dataChan` to limit pending messages. The actual limit is 2X the `MaxPendingMessages`.

https://github.com/apache/pulsar-client-go/blob/9867c29ca329302e97ddd9c6a99f66853c7f447f/pulsar/producer_partition.go#L148

### PR DESCRIPTION
**Pull request by Gleiphir2769**
Fixes #1067 

### Motivation

wait to edit...

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by gunli** [comment]
Hi @Gleiphir2769, as discussed in  #1055 , we will move some logic from `internalSend()` back to `internalAsyncSend()`, reserving resource for the requset will be done before putting it into dataChan, if there is enough semaphore and pending queue spaces, continue, or it will be block or failed, as the JAVA client did, and this will be not a problem any more.

**Comment by Gleiphir2769** [comment]
> we will move some logic from internalSend() back to internalAsyncSend(), reserving resource for the requset will be done before putting it into dataChan

If we have made some progress in this work, this PR can be closed. But I think we should fix the existing bugs first and this fix has no side effects on this work. What do you think? @gunli

**Comment by gunli** [comment]
> If we have made some progress in this work, this PR can be closed. But I think we should fix the existing bugs first and this fix has no side effects on this work. What do you think? @gunli

@Gleiphir2769 I will do the refactoring work this week.

**Comment by Gleiphir2769** [comment]
> I will do the refactoring work this week.
Good! I will close this PR after your refactor work.

**Comment by gunli** [comment]
@Gleiphir2769 I have pushed the PR #1071 , please help to review it, thanks!

**Comment by tisonkun** [comment]
Closing...

You may review #1121 and I still think that we can have a much better solution than even after #1121 merged.

**Pull request closed without merging**
