### PR TITLE
[Refactor] group current project import packages and unify the format of the comments

### PR DESCRIPTION
**Pull request by gunli**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

1. group current project import packages with go imports; 
2. unify the format of the comments with go fmt.

### Modifications

1. group current project import packages; 
2. unify the format of the comments.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by gunli** [comment]
@tisonkun Hi tison, please TAL at this PR, thanks.

**Comment by tisonkun** [comment]
Do we have a CI workflow to guard this style? If not, I tend to leave the style as is since it's not converged.

**Review by RobertIndie — CHANGES_REQUESTED** [review]
Please update linters rule in https://github.com/apache/pulsar-client-go/blob/master/.golangci.yml to guard the style.

**Comment by gunli** [comment]
> Do we have a CI workflow to guard this style? If not, I tend to leave the style as is since it's not converged.

@tisonkun Sine there is no common tools can enforce this rule, I will close this PR.

**Pull request closed without merging**
