### PR TITLE
[Fix] return when registerSendOrAckOp() failed

### LINKED ISSUE #1040: [Bug] Should we return when  `transactionImpl.registerSendOrAckOp()` returns an error?
#### Expected behavior

Should we return when  `transactionImpl.registerSendOrAckOp()` returns an error?

#### Actual behavior
Keep going when  `transactionImpl.registerSendOrAckOp()` returns an error, is this a bug?

``` go
func (p *partitionProducer) internalSendAsync(ctx context.Context, msg *ProducerMessage,
	callback func(MessageID, *ProducerMessage, error), flushImmediately bool) {
	//Register transaction operation to transaction and the transaction coordinator.
	var newCallback func(MessageID, *ProducerMessage, error)
	if msg.Transaction != nil {
		transactionImpl := (msg.Transaction).(*transaction)
		if transactionImpl.state != TxnOpen {
			p.log.WithField("state", transactionImpl.state).Error("Failed to send message" +
				" by a non-open transaction.")
			callback(nil, msg, newError(InvalidStatus, "Failed to send message by a non-open transaction."))
			return
		}

		if err := transactionImpl.registerProducerTopic(p.topic); err != nil {
			callback(nil, msg, err)
			return
		}
		if err := transactionImpl.registerSendOrAckOp(); err != nil {
			callback(nil, msg, err)
                        //Should WE RETURN HERE ???
		}
		newCallback = func(id MessageID, producerMessage *ProducerMessage, err error) {
			callback(id, producerMessage, err)
			transactionImpl.endSendOrAckOp(err)
		}
	} else {
		newCallback = callback
	}
	if p.getProducerState() != producerReady {
		// Producer is closing
		newCallback(nil, msg, errProducerClosed)
		return
	}

	// bc only works when DisableBlockIfQueueFull is false
	bc := make(chan struct{})

	// callbackOnce make sure the callback is only invoked once in chunking
	callbackOnce := &sync.Once{}
	var txn *transaction
	if msg.Transaction != nil {
		txn = (msg.Transaction).(*transaction)
	}
	sr := &sendRequest{
		ctx:              ctx,
		msg:              msg,
		callback:         newCallback,
		callbackOnce:     callbackOnce,
		flushImmediately: flushImmediately,
		publishTime:      time.Now(),
		blockCh:          bc,
		closeBlockChOnce: &sync.Once{},
		transaction:      txn,
	}
	p.options.Interceptors.BeforeSend(p, msg)

	p.dataChan <- sr

	if !p.options.DisableBlockIfQueueFull {
		// block if queue full
		<-bc
	}
}
```

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

### PR DESCRIPTION
**Pull request by gunli**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #1040

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #1040

### Motivation

fix #1040, return when registerSendOrAckOp() return an error.

### Modifications

- modified: pulsar/producer_partition.go

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by shibd** [comment]
It's better to add a unit test to cover it.

**Review by RobertIndie — APPROVED** [review]

**Comment by gunli** [comment]
@RobertIndie pls merge this PR, I have rebase it to the newest master branch.

**Comment by gunli** [comment]
@shibd @RobertIndie it seems the CI is broken.

**Comment by RobertIndie** [comment]
We need to wait for the CI to be passed before merging the PR. I have rerun the CI. @gunli

**Comment by gunli** [comment]
@RobertIndie the comments/imports of this project are of different formats, some comments looks like this:
// this is a comment
and others looks like this:
//this is a comment

some imports are grouped/sorted by names/std/third-party/projects, some are not grouped/sorted.
 
Would you please standardize the format of comments/imports in the code, otherwise, When I prepare a PR, my IDE(goland) format the comments/imports with one format, and then I have to revert the comments/imports with another editor, it quite painful for me.

**Comment by RobertIndie** [comment]
Hi, @gunli. Did you configure the code style of your IDE correctly? I usually use the `golangci-lint run --fix` to format the code.

**Comment by gunli** [comment]
@RobertIndie What I mean is that since Go have provided so many good formatting tools, as a project, it is better to have only ONE format for comments/imports, but currently there are different comment/import formats in our files, it not good for the community contributors.

**Comment by RobertIndie** [comment]
@gunli We already have the format convention for the project: https://github.com/apache/pulsar-client-go/blob/master/.golangci.yml . But it seems that currently, there are no restriction rules in place for certain cases like comment formats. But we have the `goimports` linter. If you are willing to improve this, I'm happy to review it. :)

**Pull request merged**
