### PR TITLE
Add 0.11.0 change log

### PR DESCRIPTION
**Pull request by RobertIndie**
### Motivation

Add 0.11.0 change log

**Note: This PR shouldn't be merged until the release vote is passed.**

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by gunli** [comment]
hi @RobertIndie , pls remember to merge #1045 #1047, and I will ask @zengguan to fix #1042

**Comment by RobertIndie** [comment]
Hi @gunli, The first candidate of v0.11.0 is already out: https://lists.apache.org/thread/mpjr8c6f8nk1wsjt97q0fkhf44kjvb6j
Only regression bug fixes or changes with higher scrutiny could be considered included into the v0.11.0. If you think that these PRs/Issues match this policy, please leave your request under this email: https://lists.apache.org/thread/mpjr8c6f8nk1wsjt97q0fkhf44kjvb6j Thanks.

**Comment by gunli** [comment]
OK, I have no apache ID, I will summit PR later

**Review by shibd — APPROVED** [review]

**Comment by RobertIndie** [comment]
Just see that this PR is merged before the vote. But please leave your suggested changes for the change log in this PR during the voting process. If there are any suggested changes, I will push another PR to fix it.

**Comment by gunli** [comment]
@RobertIndie it seems you forget to list me in the `Now contributors` list :)

**Comment by RobertIndie** [comment]
> it seems you forget to list me in the Now contributors list :)

Thanks! This is generated from the GitHub release. I'm not sure why it doesn't list you. I will push a PR to fix it.

**Pull request merged**
