### PR TITLE
fix: enhance transaction functionality

### PR DESCRIPTION
**Pull request by reugn**
### Motivation
Various fixes and refactoring for transaction.

### Modifications

* Employ context in the `Commit` and `Abort` methods
* Use client operation timeout
* Use `atomic.Int32` for the state
* Make all state reads atomic
* Clean up and improve error messages

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API: (yes / **no**)
  - The schema: (yes / **no** / don't know)
  - The default values of configurations: (yes / **no**)
  - The wire protocol: (yes / **no**)

### Documentation

  - Does this pull request introduce a new feature? (yes / **no**)

### CODE REVIEW

**Review by RobertIndie — APPROVED** [review]
Thanks for your PR. Good work!

**Comment by RobertIndie** [comment]
Can you help resolve the conflict? @reugn

**Comment by reugn** [comment]
@RobertIndie, resolved.

**Comment by crossoverJie** [comment]
@reugn Please check the CI results

**Comment by reugn** [comment]
@crossoverJie, please approve the CI workflows.

**Pull request merged**
