### PR TITLE
add 0.9.0 release changelog

### PR DESCRIPTION
**Pull request by freeznet**
### Motivation

- add 0.9.0 changelog
- bump VERSION and stable version

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by freeznet** [comment]
@wolfstudy could you please help to link the issue? thanks.

**Review by merlimat — APPROVED** [review]

**Comment by wolfstudy** [comment]
> @wolfstudy could you please help to link the issue? thanks.

https://github.com/apache/pulsar-client-go/pull/777Here, we introduce the function of AckResponse, but the modification of this function blocks the original unit test, so this piece of logic needs to be refactored

**Review by wolfstudy — APPROVED** [review]
LGTM +1

**Pull request merged**
