### PR TITLE
[PR-1071-1] rename pendingItem.Complete() to  pendingItem.done()

### PR DESCRIPTION
**Pull request by gunli**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #1071

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #1071

### Motivation

Spilt PR #1071 into multiple ones, this is the FIRST one.

#1071 is a BIG PR, it refactor the sending logic, here we just rename `pendingItem.Complete()` to `pendingItem.done()` , and we will add `sendRequest.done()` in #1110 to make them have the same name and meaning.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by gunli** [comment]
@tisonkun @RobertIndie @Gleiphir2769 @nodece

**Review by tisonkun — COMMENTED** [review]
Why do we need this change? May you write a brief description?

If it has a reason, this should be good to go.

**Comment by gunli** [comment]
> #1071 is a BIG PR, it refactor the sending logic, here we just rename `pendingItem.Complete()` to `pendingItem.done()` , and we will add `sendRequest.done()` in #1110 to make they have the same name and meaning.

@tisonkun I have updated the motivation.

**Review by tisonkun — APPROVED** [review]
LGTM. Pending for merging..

**Pull request merged**
