### PR TITLE
[auth] Add Athenz authentication provider

### PR DESCRIPTION
**Pull request by equanz**
### Motivation
Support Athenz authentication at pulsar-client-go.

### Modifications
Add Athenz provider into `pulsar/internal/auth`, and fix to run `Provider.Init()` in `newClient()` function.

### Verifying this change
- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
  - Added unit test for Athenz Authentication Provider

(It seems that the project should add integration test into `client_impl.go`. However, integrating with Athenz isn't simple...)

### Does this pull request potentially affect one of the following parts:
*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)

### Documentation
  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (not documented)
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by nkurihar** [comment]
LGTM

**Comment by equanz** [comment]
run integration tests

**Comment by equanz** [comment]
@wolfstudy @merlimat 
Could you review this please?

In this PR, fixed `parseParams()`, and `Provider.Init()` to run.

**Comment by hrsakai** [comment]
run integration tests

**Pull request merged**
